# Предобработка данных


задача - вытащить данные из двух датасетов, проставить лейблы (fake = 0, true = 1), смерджить в один датасет, зашаффлить строки

In [1]:
# ячейка импортов

import numpy as np
import pandas as pd

In [14]:
# читаем данные

data_fake = pd.read_csv('/Users/macbook/Documents/datasets/news/Fake.csv',
                        encoding='utf-8')

# добавим колонку -- тип новости (true = 1, fake = 0)
data_fake['label'] = 0
data_fake.head(3)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017"

In [18]:
# теперь для тру-новостей

data_true = pd.read_csv('/Users/macbook/Documents/datasets/news/True.csv',
                        encoding='utf-8')

data_true['label'] = 1 # лейбл тру-новостей
data_true.head(3)

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1

In [30]:
# мерджим датафреймы
data = data_fake.append(data_true)
data

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [35]:
# шаффлим строки

from sklearn.utils import shuffle
data = shuffle(data).reset_index(drop=True)
data

,title,text,subject,date,label
0,ADVISORY: Story on Kushner visiting Iraq withd...,(Reuters) - The story “Trump son-in-law Jared ...,politicsNews,"April 3, 2017",1
1,Kasich campaign denies report of Romney endors...,WASHINGTON (Reuters) - Republican presidential...,politicsNews,"March 14, 2016",1
2,WATCH: Colbert Devises Perfect Advertisement ...,If America is going to end the day Donald Trum...,News,"May 20, 2016",0
3,Trump says hopes for Cuban 'freedom' after Cas...,"WEST PALM BEACH, Fla. (Reuters) - U.S. Preside...",politicsNews,"November 26, 2016",1
4,Trump Whines Pathetically On Twitter Because ...,"Well, it seems that despite the efforts of not...",News,"July 17, 2017",0
...,...,...,...,...,...
44893,Germany Releases Memo Showing How Destructive...,Donald Trump s economic proposals would be dis...,News,"October 1, 2016",0
44894,"Trump says unnamed country plans to build, exp...",INDIANAPOLIS (Reuters) - President Donald Trum...,politicsNews,"September 27, 2017",1
44895,LAURA INGRAHAM: GOP Senators In Private Meetin...,During a private meeting of the most senior Re...,politics,"Oct 11, 2017",0
44896,Palestinian billionaire Masri detained in Saud...,"AMMAN (Reuters) - Sabih al-Masri, Jordan s mos...",worldnews,"December 16, 2017",1
44897,Lebanese president said Hariri will visit Pari...,BEIRUT (Reuters) - Lebanese President Michel A...,worldnews,"November 16, 2017",1

In [36]:
# сохраняем в csv
data.to_csv("news_fake-n-true.csv")